[build]
  publish = "dist"
  command = "npm run build"
  functions = "netlify/functions"

[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE"

[functions]
  node_bundler = "esbuild"

# Redirecciones para Vite SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200